
const menu=document.querySelector('.menu'),links=document.querySelector('.links');if(menu)menu.onclick=()=>links.classList.toggle('open');
const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.dot')];let cur=0;
function show(i){slides.forEach((s,x)=>s.classList.toggle('active',x===i));dots.forEach((d,x)=>d.classList.toggle('on',x===i));cur=i}
dots.forEach((d,i)=>d.onclick=()=>show(i));if(slides.length)setInterval(()=>show((cur+1)%slides.length),5000);
const af=document.getElementById('accountForm');if(af)af.addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('n').value,m=document.getElementById('m').value,s=document.getElementById('s').value,b=document.getElementById('b').value;const t=`Online Account Enquiry%0AName: ${encodeURIComponent(n)}%0AMobile: ${encodeURIComponent(m)}%0AScheme: ${encodeURIComponent(s)}%0ABudget: ${encodeURIComponent(b)}`;window.open(`https://wa.me/918208400944?text=${t}`,'_blank')});


// Full-screen image lightbox for hero, scheme and gallery images.
(()=>{const box=document.getElementById('imageLightbox'),view=document.getElementById('lightboxImage'),cap=document.getElementById('lightboxCaption');if(!box||!view)return;const imgs=[...document.querySelectorAll('.hero .slide img,.schemegrid .card img,.gallery img,.mission img')];let at=0;function open(i){at=i;const img=imgs[at];view.src=img.src;view.alt=img.alt||img.closest('article')?.querySelector('h3')?.textContent||'Society image';cap.textContent=view.alt;box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function close(){box.classList.remove('open');box.setAttribute('aria-hidden','true');document.body.style.overflow=''}function move(n){open((at+n+imgs.length)%imgs.length)}imgs.forEach((img,i)=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','पूरा चित्र देखें');img.addEventListener('click',()=>open(i));img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(i)}})});box.querySelector('.lightbox-close').onclick=close;box.querySelector('.lightbox-prev').onclick=()=>move(-1);box.querySelector('.lightbox-next').onclick=()=>move(1);box.addEventListener('click',e=>{if(e.target===box)close()});document.addEventListener('keydown',e=>{if(!box.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)})})();
